user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
    worker_connections 65535;
}

http {
    include mime.types;
    default_type application/octet-stream;

    large_client_header_buffers 8 64k;
    client_header_buffer_size 64k;
    client_max_body_size 64m;
    ignore_invalid_headers off;

    access_log off;
    error_log /var/log/nginx/error.log crit;

    # ========== UPSTREAM: HAProxy ==========
    upstream haproxy_backend {
        server 127.0.0.1:31337;
    }

    # ========== MAIN SERVER ==========
    server {
        listen 80 default_server;
        server_name _;

        server_tokens off;

        location / {
            proxy_pass http://haproxy_backend;
            proxy_http_version 1.1;

            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header CF-Connecting-IP $remote_addr;

            proxy_connect_timeout 10s;
            proxy_read_timeout 10s;
            proxy_send_timeout 10s;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            proxy_intercept_errors on;
            error_page 502 503 504 = @dummy_fallback;
        }

        location @dummy_fallback {
            root /var/www/html/www;
            index index.html;
            try_files /index.html =444;
        }

#        location /assets/ {
#            root /var/www/html/www;
#            access_log off;
#            expires 30d;
#        }

#        location ~* \.(css|js|png|ico|svg|webp|jpg|jpeg|gif|woff|woff2|ttf|eot|otf)$ {
#            root /var/www/html/www;
#            access_log off;
#            expires 30d;
#        }

        location = /robots.txt {
            root /var/www/html/www;
        }

        location = /sitemap.xml {
            root /var/www/html/www;
        }
    }
}
